export const Months = [
  {
    nameGeo: 'იანვარი',
    nameLat: 'January',
    nameGeoShort: 'იან',
    nameLatShort: 'Jan',
    value: 0,
  },
  {
    nameGeo: 'თებერვალი',
    nameLat: 'February',
    nameGeoShort: 'თებ',
    nameLatShort: 'Feb',
    value: 1,
  },
  {
    nameGeo: 'მარტი',
    nameLat: 'January',
    nameGeoShort: 'მარ',
    nameLatShort: 'Jan',
    value: 2,
  },
  {
    nameGeo: 'აპრილი',
    nameLat: 'January',
    nameGeoShort: 'აპრ',
    nameLatShort: 'Jan',
    value: 3,
  },
  {
    nameGeo: 'მაისი',
    nameLat: 'January',
    nameGeoShort: 'მაი',
    nameLatShort: 'Jan',
    value: 4,
  },
  {
    nameGeo: 'ივნისი',
    nameLat: 'January',
    nameGeoShort: 'ივნ',
    nameLatShort: 'Jan',
    value: 5,
  },
  {
    nameGeo: 'ივლისი',
    nameLat: 'January',
    nameGeoShort: 'ივლ',
    nameLatShort: 'Jan',
    value: 6,
  },
  {
    nameGeo: 'აგვისტო',
    nameLat: 'January',
    nameGeoShort: 'აგვ',
    nameLatShort: 'Jan',
    value: 7,
  },
  {
    nameGeo: 'სექტემბერი',
    nameLat: 'January',
    nameGeoShort: 'სექ',
    nameLatShort: 'Jan',
    value: 8,
  },
  {
    nameGeo: 'ოქტომბერი',
    nameLat: 'January',
    nameGeoShort: 'ოქტ',
    nameLatShort: 'Jan',
    value: 9,
  },
  {
    nameGeo: 'ნოემბერი',
    nameLat: 'January',
    nameGeoShort: 'ნოე',
    nameLatShort: 'Jan',
    value: 10,
  },
  {
    nameGeo: 'დეკემბერი',
    nameLat: 'January',
    nameGeoShort: 'დეკ',
    nameLatShort: 'Jan',
    value: 11,
  },
];
